const PROMPTS = [
  "Name a fruit",
  "Name an animal",
  "Name a color",
  "Name something at the beach",
  "Name a superhero",
  "Name a country",
  "Name a sport",
  "Name a movie genre",
  "Name something in a kitchen",
  "Name a music instrument",
  "Name a planet",
  "Name something cold",
  "Name a dessert",
  "Name something you do in the morning",
  "Name a vehicle",
  "Name something you find in a classroom",
  "Name a season",
  "Name a body part",
  "Name a holiday",
  "Name something round",
  "Name a drink",
  "Name an emotion",
  "Name a famous city",
  "Name something that flies",
  "Name a flower",
  "Name something sweet",
  "Name a pizza topping",
  "Name something you wear",
  "Name a day of the week",
  "Name something scary",
  "Name a board game",
  "Name something in a park",
  "Name a school subject",
  "Name an ocean creature",
  "Name something you find in a wallet",
  "Name a breakfast food",
  "Name something that makes noise",
  "Name a social media platform",
  "Name something you do on vacation",
  "Name a cartoon character",
  "Name a tree",
  "Name something found in space",
  "Name a musical genre",
  "Name a hobby",
  "Name a wild animal",
  "Name a shape",
  "Name a piece of furniture",
  "Name a vegetable",
  "Name a mountain",
  "Name a famous person",
  "Name something you find in a gym",
  "Name a brand of shoes",
  "Name something you find in a bathroom",
  "Name a mythical creature",
  "Name a scientific discovery",
  "Name something that smells good",
  "Name an expensive item",
  "Name something you find in a purse",
  "Name a classic book",
  "Name a famous landmark",
  "Name a type of weather",
  "Name a household appliance",
  "Name something you find in a toolbox",
  "Name a favorite pastime",
  "Name a type of pasta",
  "Name something you find in a garden",
  "Name a famous painter",
  "Name something you do to relax",
  "Name a kind of candy",
  "Name a movie villain",
  "Name a piece of tech",
  "Name something you find in a bank",
  "Name a type of cheese",
  "Name a favorite holiday tradition",
  "Name a type of dance",
  "Name a mode of transportation",
  "Name something you find in a library",
  "Name a type of cloud",
  "Name a famous athlete",
  "Name a something you find in a backyard",
  "Name a type of cookie",
  "Name a famous explorer",
  "Name something you do on a rainy day",
  "Name a favorite breakfast cereal",
  "Name a type of bird",
  "Name a something you find in a garage",
  "Name a famous inventor",
  "Name a piece of jewelry",
  "Name a something you find in a attic",
  "Name a type of music festival",
  "Name a favorite summer activity",
  "Name a type of soup",
  "Name something you find in a desert",
  "Name a famous scientist",
  "Name a piece of clothing you find in a closet",
  "Name a favorite weekend activity",
  "Name a type of snack food",
  "Name a something you find in a basement",
  "Name a famous author",
  "Name a piece of sports equipment",
  "Name a something you find in a forest",
  "Name a type of sandwich",
  "Name a favorite winter activity",
  "Name a piece of artwork",
  "Name a something you find in a city",
  "Name a favorite spring activity",
  "Name a piece of music",
  "Name a something you find in a village",
  "Name a type of beverage",
  "Name a favorite autumn activity",
  "Name a piece of historical technology",
  "Name a something you find in an office",
  "Name a type of salad",
  "Name a favorite childhood game",
  "Name a piece of office equipment",
  "Name a something you find in a theatre",
  "Name a type of fruit juice",
  "Name a favorite way to exercise",
  "Name a piece of playground equipment",
  "Name a something you find in a hospital",
  "Name a type of nut",
  "Name a favorite vacation spot",
  "Name a piece of camera gear",
  "Name a something you find in a restaurant",
  "Name a type of tea",
  "Name a favorite way to travel",
  "Name a piece of luggage",
  "Name a something you find in a museum",
  "Name a type of bread",
  "Name a favorite type of party",
  "Name a piece of cleaning equipment",
  "Name a something you find in a zoo",
  "Name a type of herb",
  "Name a favorite form of entertainment",
  "Name a piece of camping gear",
  "Name a something you find in a space station",
  "Name a type of spice",
  "Name a favorite work of literature",
  "Name a something you find in a laboratory",
  "Name a type of yogurt",
  "Name a favorite historical era",
  "Name a piece of kitchen equipment",
  "Name a something you find in a factory",
  "Name a type of milk",
  "Name a favorite scientific theory",
  "Name a piece of laboratory equipment",
  "Name a something you find in a observatory",
  "Name a type of honey",
  "Name a favorite piece of technology",
  "Name a piece of medical equipment",
  "Name a something you find in a cockpit",
  "Name a type of fabric",
  "Name a favorite architectural style",
  "Name a piece of construction equipment",
  "Name a something you find in a engine room",
  "Name a type of fossil",
  "Name a favorite geological feature",
  "Name a piece of farm equipment",
  "Name a something you find in a barn",
  "Name a type of stone",
  "Name a favorite astronomical object",
  "Name a piece of mining equipment",
  "Name a something you find in a mine",
  "Name a type of fish",
  "Name a favorite ecological habitat",
  "Name a piece of oceanic equipment",
  "Name a something you find in a coral reef",
  "Name a favorite biological process",
  "Name a piece of botanical equipment",
  "Name a something you find in a greenhouse",
  "Name a favorite chemical element",
  "Name a piece of chemical equipment",
  "Name a something you find in a refinery",
  "Name a type of metal",
  "Name a favorite physical phenomenon",
  "Name a piece of physics equipment",
  "Name a something you find in a particle accelerator",
  "Name a type of gas",
  "Name a favorite mathematical concept",
  "Name a piece of mathematical equipment",
  "Name a something you find in a classroom",
  "Name a type of liquid",
  "Name a favorite astronomical event",
  "Name a piece of astronomical equipment",
  "Name a something you find in a telescope",
  "Name a type of radiation",
  "Name a favorite subatomic particle",
  "Name a piece of particle accelerator equipment",
  "Name a something you find in a vacuum chamber",
  "Name a type of plasma",
  "Name a favorite astronomical survey",
  "Name a piece of space exploration equipment",
  "Name a something you find in a rover",
  "Name a type of dark matter",
  "Name a favorite cosmological model",
  "Name a piece of cosmological equipment",
  "Name a something you find in a gravitational wave detector",
  "Name a type of galaxy",
  "Name a favorite stellar object",
  "Name a something you find in a supernova remnant",
  "Name a favorite solar system object",
  "Name a something you find in an asteroid belt",
  "Name an ice cream flavor",
  "Name a soda brand",
  "Name a fast food chain",
  "Name a brand of cereal",
  "Name a favorite sandwich ingredient",
  "Name a favorite snack",
  "Name a type of seafood",
  "Name a favorite pasta dish",
  "Name a favorite healthy food",
  "Name a favorite international cuisine",
  "Name a social media app",
  "Name a type of software",
  "Name a piece of hardware",
  "Name a favorite website",
  "Name a favorite gadget",
  "Name a piece of audio equipment",
  "Name a favorite streaming service",
  "Name a type of mobile device",
  "Name a favorite computer peripheral",
  "Name a piece of networking equipment",
  "Name a favorite programming language",
  "Name a something you find on a desk",
  "Name a type of digital file",
  "Name a favorite emoji",
  "Name a piece of wearable tech",
  "Name a favorite cloud service",
  "Name a type of data storage",
  "Name a favorite security feature",
  "Name a piece of smart home technology",
  "Name a favorite AI tool",
  "Name a type of virtual reality hardware",
  "Name a favorite online community",
  "Name a something you find in a data center",
  "Name a favorite tech company",
  "Name a piece of software for creativity",
  "Name a favorite online learning platform",
  "Name a something you find in a startup office",
  "Name a favorite digital trend",
  "Name a piece of telecommunications gear",
  "Name a favorite online marketplace",
  "Name a something you find in a technical manual",
  "Name a type of cryptocurrency",
  "Name a favorite blockchain project",
  "Name a something you find in a computer lab",
  "Name a favorite robotic invention",
  "Name a favorite way to learn new tech",
  "Name a something you find in a science museum",
  "Name a favorite tech influencer",
  "Name a piece of vintage electronics",
  "Name a something you find in a thrift store",
  "Name a favorite futuristic concept",
  "Name a piece of space-age technology",
  "Name a something you find in a sci-fi movie",
  "Name a favorite quote about technology",
  "Name a something you find in a repair shop",
  "Name a favorite tech event",
  "Name a piece of high-tech gear",
  "Name a something you find in a secret lab",
  "Name a favorite open-source project",
  "Name a something you find in a software engineer's room",
  "Name a favorite way to debug code",
  "Name a something you find in a developer's backpack",
  "Name a piece of gear for a remote worker",
  "Name a something you find in a home office",
  "Name a favorite collaboration tool",
  "Name a something you find in a code repository",
  "Name a favorite software design pattern",
  "Name a something you find in a technical documentation",
  "Name a favorite tech stack component",
  "Name a something you find in a tech conference bag",
  "Name a favorite part of being a developer",
  "Name a something you find in a coding competition",
  "Name a favorite technical challenge",
  "Name a something you find in a hackathon project",
  "Name a movie",
  "Name a TV show",
  "Name a book",
  "Name a song",
  "Name an artist",
  "Name a band",
  "Name a celebrity",
  "Name a director",
  "Name an actor",
  "Name an actress",
  "Name a writer",
  "Name a podcast",
  "Name a magazine",
  "Name a comic book",
  "Name a musical",
  "Name a theater play",
  "Name a documentary",
  "Name a reality TV show",
  "Name a news source",
  "Name a YouTube channel",
  "Name a social media star",
  "Name a sports team",
  "Name a fashion brand",
  "Name a designer",
  "Name a photographer",
  "Name an architect",
  "Name a public speaker",
  "Name a historical figure",
  "Name an event in history",
  "Name a place on Earth",
  "Name a mythic place",
  "Name a character from a book",
  "Name a brand of car",
  "Name a brand of watch",
  "Name a type of hobby",
  "Name a style of architecture",
  "Name a work of art",
  "Name an instrument",
  "Name a mineral",
  "Name a kind of scent",
  "Name a type of flavor",
  "Name an sound",
  "Name an principle",
  "Name an habit",
  "Name an principle",
  "Name a principal",
  "Name a role model",
  "Name a visionary",
  "Name a peacemaker",
  "Name a adventurer",
  "Name a believer",
  "Name a support",
  "Name a observer",
  "Name a seeker",
  "Name a traveler",
  "Name a survivor",
  "Name a dreamer",
  "Name a thinker",
  "Name a doer",
  "Name a mystery",
  "Name a wonder",
  "Name a beauty",
  "Name a truth",
  "Name a light",
  "Name a power",
  "Name a freedom",
  "Name a justice",
  "Name a hope",
  "Name a future",
  "Name a journey",
  "Name a story",
  "Name a world",
  "Name a universe",
  "Name a anything",
  "Name a symbol",
  "Name a system",
  "Name a pattern",
  "Name a evolution",
  "Name a cycle",
  "Name a balance",
  "Name a miracle",
  "Name a reality",
  "Name an illusion"
];

// Track used prompt indices to avoid repeats within a session
let usedIndices: Set<number> = new Set();

export function getRandomPrompt(): string {
  // Reset if all prompts are used
  if (usedIndices.size >= PROMPTS.length) {
    usedIndices = new Set();
  }

  let index: number;
  do {
    index = Math.floor(Math.random() * PROMPTS.length);
  } while (usedIndices.has(index));

  usedIndices.add(index);
  return PROMPTS[index];
}

export function resetPrompts(): void {
  usedIndices = new Set();
}
